### ISSUE TITLE
Embedded videos too wide on mobile & desktop

### ISSUE THREAD

**Issue by thisisgreg** [DoSomethingArchive/dosomething-blog#79]
https://blog.dosomething.org/

![img_0099](https://cloud.githubusercontent.com/assets/5720236/5994900/ce4b216e-aa52-11e4-81bb-b872f5b2f2e7.PNG)

![img_0098](https://cloud.githubusercontent.com/assets/5720236/5994902/cfe58190-aa52-11e4-8577-cbb46cdc0457.PNG)

**Comment by weerd** [comment]
![image](https://cloud.githubusercontent.com/assets/105849/6257103/6c25c2dc-b78b-11e4-963e-53f9b62c2cff.png)

I was about to create an issue, but saw this one. Screenshot from desktop.
