### ISSUE TITLE
Update server public directory

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/dosomething-blog#84]
The changes in #83 move the "public" directory where the server should be serving files from to the `web` subdirectory. We need to update the web server to point to `/var/www/dosomething-blog/current/web` instead of `/var/www/dosomething-blog/current/`.

**Comment by DFurnes** [comment]
@sheyd Please update Nginx conf to point to the new directory above, thaaaaaaaanks! :smile_cat:

**Comment by sheyd** [comment]
@DFurnes I updated this, but it returned a "input file not specified" error on page render. I can come over and show you if it'll help with de-bugging. I've reverted the change for now back to `/current/` directory as the root dir until we can figure this out.

**Comment by DFurnes** [comment]
Sena is a god-damned champion, and we sorted this out this morning! :trophy:
